### PR TITLE
optimize code

### PR DESCRIPTION
**Pull request by Delta456**
## Things to note

- Never use capital letters for objects. Python prefers snake_case.
- Use `==` overloaded instead of `check_dims`
- Use `ValueError` instead of just returning the string.
- Use `__name__ == "__main__"` for running the script

### CODE REVIEW

**Comment by Delta456** [comment]
@soumitradev Please review

**Comment by PseudoCodeNerd** [comment]
Bruh @Delta456 original code and rep is mine.

**Comment by soumitradev** [comment]
Closing PR, if you want please make this PR to @PseudoCodeNerd's repo.

**Comment by Delta456** [comment]
Alright then

**Pull request closed without merging**
